### Booking
POST http://localhost:3000/booking
Content-Type: application/json

{
      "customerId": "68031346e7c08857694d78a5",
      "startTime": "Wed Jan 02 2025 07:00:00 GMT-0300",
      "turns": "2",
      "subTotal": 100,
      "discountRate": 0.1,
      "total": 90,
      "discountAmt": 10,
      "status": "booked",
      "cancelDeadline": "2025-01-01T09:00:00Z",
      "payDeadline": "2025-01-03T10:00:00Z",
      "items": [{
            "productId": "68031346e7c08857694d78a8",
            "quantity": 1,
            "safetyItems": {"type": "chaleco", "quantity": 2},
            "peopleCount": 2
      }]
}


### Customer
GET http://localhost:3000/customer/68017a6de5f17517c3ff4ca1
Content-Type: application/json
