#--------------- Booking ---------------#

### GET ALL
GET http://localhost:3000/booking
Content-Type: application/json

###CREATE (RESERVAR)
POST http://localhost:3000/booking
Content-Type: application/json

{
      "customerId": "681161a9f70f0b84627bbd43",
      "startTime": "Mon May 01 2025 19:46:00 GMT-0300",
      "totalTurns": 3,
      "method": "cash",
      "currency": "USD",
      "items": [{
            "productId": "68115e26f70f0b84627bbd3d",
            "quantity": 1,
            "turns": 2,
            "safetyItems": {"type": "chaleco", "quantity": 2},
            "peopleCount": 2
      },
      {
            "productId": "68115e26f70f0b84627bbd41",
            "quantity": 1,
            "turns": 1,
            //"safetyItems": {"type": "casco", "quantity": 2},
            "peopleCount": 1
      }]
}

### CANCEL (CANCELAR RESERVA)
PATCH http://localhost:3000/booking/cancel/68103afefe7a10689c71f946
Content-Type: application/json

### REFUND (PEDIR REEMBOLSO POR TORMENTA)
PATCH http://localhost:3000/booking/refund/68101a8afb6e7118511ee6e7
Content-Type: application/json

#--------------- Customer ---------------#
### GET BY ID
GET http://localhost:3000/customer/681028ca75b4f6bf749831bb
Content-Type: application/json

### GET ALL
GET http://localhost:3000/customer
Content-Type: application/json

### CREATE
POST http://localhost:3000/customer
Content-Type: application/json

{
      "name": "Shallan",
      "email": "shallan@rental.com",
      "phone": "+5491123456789"
}

#--------------- Products ---------------#
### GET ALL
GET http://localhost:3000/product
Content-Type: application/json

#--------------- Payment ---------------#
### GET ALL
GET http://localhost:3000/payment
Content-Type: application/json


### PAY WITH CASH  (PAGAR CON EFECTIVO, PASO EL ID DEL BOOKING)
POST http://localhost:3000/payment/payCash/681162f7f70f0b84627bbd80
Content-Type: application/json

{
      "amount": 23.4,
      "currency": "USD",
      "method": "cash"
}