services:

  mongo:
    image: mongo:7.0
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ./mongo_data
      o: bind